prompts: ["ignore this"]
providers:
  - id: "api:local"
    config:
      url: "http://localhost:8000/api/"
      method: POST
      headers:
        Content-Type: application/json
      body: '{"question":"{{question}}","image":null}'
tests:
  - vars:
      question: "What Python libraries should I learn for data visualization?"
  - vars:
      question: "How do I install Jupyter notebooks?"
